export const REQUEST_API_FAILED = "REQUEST_API_FAILED";
export const REQUEST_API_LOADING = "REQUEST_API_LOADING";
export const REQUEST_SUCCESS = "REQUEST_SUCCESS";
export const SET_ERROR = "SET_ERROR";
